### ISSUE TITLE
Feedback on the wording of exercices

### ISSUE THREAD

**Issue by Ninjarab** [fewlines-education/camp2_exercises#26]
`camp2_exercises/02_programming_fundamentals/03_algorithms_day_1/`
- `03_play_with_conditional_statement `
  - `01_can_i_drink_alcohol `
    - [ ] say explicitly that we are expecting a boolean
  - `02_can_i_rent_a_car `
    - [ ] say explicitly that we should use the variables assigned at the top of the file
    - [ ] say explicitly that the necessary licenses are only `B` **AND** `B1`
- `04_play_with_for_loop`
  - `01_print_numbers `
    - [ ] say explicitly that we should use a loop
    - [ ] explain `stdout`

**Comment by arnaudmorisset** [comment]
Agree with that.

I will like to add (somewhere) a sentence about using directly condition as a boolean. I see too much this:

```javascript
if (age > 18) {
  myVar = true;
} else {
  myVar = false;
}
```

instead of : `const myVar = age > 18;`
